RBAC domain model
casbin/casbin-ex pull request #10
Opened 2022-03-11 12:57 UTC by Zat42

Based on abandonned PR #5 (@ssajnani) to fix issue #4.

I removed all code styling diff to only reflect _real changes_.

2022-03-11 12:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casbin/casbin-ex?pullRequest=10) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casbin/casbin-ex?pullRequest=10) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casbin/casbin-ex?pullRequest=10) it.</sub>

2022-03-12 00:59 UTC, hsluoyz commented
@Zat42 plz fix:

![image](https://user-images.githubusercontent.com/3787410/157996896-65c56633-7683-46a2-9de2-d34780520f09.png)

2022-03-12 17:57 UTC, ngoclinhng requested changes
Please add unit tests for [rbac_with_domain](https://github.com/casbin/casbin/blob/master/examples/rbac_with_domains_model.conf). 
(FYI: here are the test cases for [rbac](https://github.com/casbin/casbin-ex/blob/master/test/enforcer/rbac_model_test.exs)).

2022-03-16 12:50 UTC, Zat42 commented
I added some tests with [rbac_with_domain](https://github.com/casbin/casbin/blob/master/examples/rbac_with_domains_model.conf) based on this [policy](https://github.com/casbin/casbin/blob/master/examples/rbac_with_domains_policy2.csv).

Also, the way @ssajnani implemented the domain logic doesn't permit to have transitive roles. Do you think I should add this information in the [README part about RBAC](https://github.com/casbin/casbin-ex/#role-base-access-control-rbac)? I will try to update this later when I have more time to do it.

2022-03-18 01:53 UTC, ngoclinhng approved these changes

2022-03-18 02:01 UTC, merged